import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { TurnCancelledError } from "../errors.js";
import { readStoredThread, writeStoredThread } from "../session-state.js";
import { TranscriptWriter } from "../transcript.js";
import type { AgentResult, RunnerOptions } from "../types.js";

/**
 * DSH (DeepSeek Harness) runner — drives a dsh `--profile sdk` subprocess over
 * stdio JSON-RPC via the official `@deepseek-ai/dsh-sdk-client` TS SDK.
 *
 * Unlike the CLI-spawn runners (gemini/opencode), this one delegates process
 * lifecycle to the SDK's `DeepSeekHarness` class. The SDK starts the subprocess
 * lazily, speaks the wire protocol, and tears it down via an EOF→SIGTERM→SIGKILL
 * ladder on `close()`.
 *
 * The platform gateway URL and API key arrive through `process.env` (planted by
 * `plantLlmEnv` in interactive.ts). The key is injected into the child env under
 * the name declared in settings.yaml's `apiKeyEnv` — the secret never enters
 * the settings file.
 *
 * Session continuity: dsh sessions are durable in $DSH_HOME; we store the
 * sessionId via readStoredThread/writeStoredThread, same as every other runner.
 *
 * Cancel: the wire protocol has no mid-turn cancel. `close()` terminates the
 * subprocess; the pending `run()` rejects with TransportClosedError, which we
 * convert to TurnCancelledError.
 */

const DSH_HOME_SUBDIR = ".dsh";
const PROVIDER_ROUTE = "ai-lubricant";
const CREDENTIAL_ENV = "LUBRICANT_API_KEY";

type DshNotification = {
  method: string;
  params: Record<string, unknown>;
};

type DshSessionEvent = {
  type: string;
  seq?: number;
  data?: Record<string, unknown>;
};

type ContentBlock = {
  type: string;
  text?: string;
  id?: string;
  name?: string;
  arguments?: string;
  content?: ContentBlock[];
  isError?: boolean;
  toolCallId?: string;
};

type DshRunResult = {
  sessionId: string;
  finalResponse: string;
  events?: unknown[];
  notifications?: unknown[];
};

export class DshRunner {
  private readonly writer = new TranscriptWriter();
  private finalText = "";

  constructor(private readonly options: RunnerOptions) {}

  private dshHome(): string {
    return path.join(this.options.home, DSH_HOME_SUBDIR);
  }

  /**
   * Write $DSH_HOME/settings.yaml with a provider route pointing at the
   * platform gateway. Credential is referenced by env var name (apiKeyEnv),
   * never written to the file. Rewritten each turn so model changes take
   * effect (dsh hot-reloads settings.yaml per request).
   */
  async writeSettingsFile(): Promise<void> {
    if (this.options.systemEnv) {
      // system-env: don't clobber the operator's ~/.dsh/settings.yaml
      return;
    }
    const dshHome = this.dshHome();
    await fs.mkdir(dshHome, { recursive: true });

    const endpoint = process.env.LLM_API_ENDPOINT || process.env.OPENAI_BASE_URL || "";
    const model = this.options.model || process.env.LLM_MODEL || "";
    if (!endpoint) {
      throw new Error("dsh runner requires LLM_API_ENDPOINT");
    }
    if (!model) {
      throw new Error("dsh runner requires a model");
    }

    // Ensure /v1 suffix for OpenAI-completions wire format
    let baseURL = endpoint.replace(/\/+$/, "");
    if (!baseURL.endsWith("/v1")) {
      baseURL += "/v1";
    }

    const settings = `# Generated by agent-compose runtime — points dsh at the platform gateway.
llm-pi-ai:
  providers:
    ${PROVIDER_ROUTE}:
      displayName: Ai Lubricant
      api: openai-completions
      baseURL: ${baseURL}
      apiKeyEnv: ${CREDENTIAL_ENV}
      models:
        - id: ${model}
          name: ${model}
          contextWindow: 1000000
          maxTokens: 65536
      retryPolicy:
        mode: normal
        maxRetries: 2
`;
    await fs.writeFile(path.join(dshHome, "settings.yaml"), settings, "utf-8");
  }

  private emitItem(item: Record<string, unknown> & { id: string; type: string }): void {
    this.options.emit?.("agent_event", { agent_id: "", item });
  }

  private handleNotification(notification: DshNotification): void {
    const emit = this.options.emit;
    if (!emit) return;

    // session.status: whole-agent running/idle transitions
    if (notification.method === "session.status") {
      const status = String(notification.params?.status || "");
      if (status === "running") {
        emit("agent_turn_started", { provider: "dsh", messageId: "", deliveryAttempt: 1 });
      } else if (status === "idle") {
        emit("agent_turn_completed", { provider: "dsh", stopReason: "completed" });
      }
      return;
    }

    // subagent.started/finished: in-runtime child sessions
    if (notification.method === "subagent.started" || notification.method === "subagent.finished") {
      const p = notification.params;
      emit("agent_event", {
        agent_id: String(p.childSessionId || ""),
        item: {
          id: String(p.childSessionId || randomUUID()),
          type: notification.method === "subagent.started" ? "subagent_started" : "subagent_finished",
          ...p,
        },
      });
      return;
    }

    // session.event: the main conversation stream — filter and map
    if (notification.method !== "session.event") return;

    const sessionEvent = notification.params?.event as DshSessionEvent | undefined;
    if (!sessionEvent) return;

    const eventType = String(sessionEvent.type || "");
    const data = (sessionEvent.data || {}) as Record<string, unknown>;
    const seq = sessionEvent.seq;

    switch (eventType) {
      case "assistant/message": {
        const message = data.message as
          | { content?: ContentBlock[]; id?: string }
          | undefined;
        if (!message) break;
        const content = Array.isArray(message.content) ? message.content : [];
        for (const block of content) {
          const blockType = String(block.type || "");
          const id = String(block.id || message.id || `dsh-${seq}`);
          if (blockType === "text") {
            const text = String(block.text || "");
            if (text) {
              this.finalText = text;
              this.writer.write(text);
              this.emitItem({ id, type: "agent_message", text });
            }
          } else if (blockType === "reasoning") {
            this.emitItem({ id, type: "reasoning", text: String(block.text || "") });
          } else if (blockType === "tool-call") {
            this.emitItem({
              id,
              type: "tool_call",
              title: String(block.name || ""),
              input: block.arguments,
              status: "running",
            });
          }
        }
        break;
      }
      case "tool/call": {
        const callId = String(data.callId || `dsh-${seq}`);
        this.emitItem({
          id: callId,
          type: "tool_call",
          title: String(data.name || ""),
          input: data.arguments,
          status: "running",
        });
        break;
      }
      case "tool/result": {
        const message = data.message as
          | { source?: { callId?: string }; content?: ContentBlock[] }
          | undefined;
        const callId = String(message?.source?.callId || `dsh-${seq}`);
        const content = Array.isArray(message?.content) ? message!.content : [];
        let output = "";
        let isError = false;
        for (const block of content) {
          if (block.type === "tool-result") {
            isError = isError || block.isError === true;
            const inner = Array.isArray(block.content) ? block.content : [];
            for (const ib of inner) {
              if (ib.type === "text") output += String(ib.text || "");
            }
          }
        }
        this.emitItem({
          id: callId,
          type: "tool_call",
          title: "",
          output,
          status: isError ? "error" : "done",
        });
        break;
      }
      // Filter: system/message, user/message (non-user source / skill injection),
      // session/title, turn/*, step/*, request/*, agent/inbox/spliced — internal
      // lifecycle, not conversation content for the client.
      default:
        break;
    }
  }

  async runPrompt(promptText: string): Promise<AgentResult> {
    if (this.options.outputSchema) {
      throw new Error("structured JSON output is not supported by dsh runner");
    }

    const result: AgentResult = {
      provider: "dsh",
      threadId: "",
      stopReason: "completed",
      finalText: "",
      transcript: "",
      stderr: "",
    };

    const userPrompt = this.options.systemContext
      ? `${this.options.systemContext}\n\n${promptText}`
      : promptText;

    await this.writeSettingsFile();

    // Lazy import so the package isn't required at module load time (matches
    // the claude runner's `await import("@anthropic-ai/claude-agent-sdk")`).
    const { DeepSeekHarness } = await import("@deepseek-ai/dsh-sdk-client");

    const dshHome = this.dshHome();
    const model = this.options.model || process.env.LLM_MODEL || "";

    const harness = new DeepSeekHarness({
      profile: "sdk",
      provider: PROVIDER_ROUTE,
      model,
      cwd: this.options.workspace,
      dshHome,
      maxTokens: 49152,
      initializeTimeoutMs: 60000,
      // SDK env replaces the parent environment entirely — only pass what dsh
      // needs: PATH for executables, HOME for Node, the credential, and
      // DSH_HOME (the SDK also sets it from `dshHome`, but being explicit is
      // safe since env replaces entirely).
      env: {
        PATH: process.env.PATH || "",
        HOME: process.env.HOME || process.env.USERPROFILE || "",
        [CREDENTIAL_ENV]: process.env.LLM_API_KEY || "",
        DSH_HOME: dshHome,
        ...(process.env.SYSTEMROOT ? { SYSTEMROOT: process.env.SYSTEMROOT } : {}),
      },
    });

    // Cancel: wire abort signal to harness.close(). The wire has no mid-turn
    // cancel; close() kills the subprocess, making run() reject.
    const onAbort = () => {
      void harness.close().catch(() => {});
    };
    this.options.abortController?.signal.addEventListener("abort", onAbort);

    // Restore session thread
    const stored = await readStoredThread(
      this.options.stateRoot,
      "dsh",
      this.options.sessionScope,
    );
    const sessionId = stored?.threadId || `dsh-${Date.now()}`;

    try {
      const runResult = (await harness.run(userPrompt, {
        sessionId,
        onNotification: (n: DshNotification) => this.handleNotification(n),
      })) as DshRunResult;
      result.threadId = runResult.sessionId || sessionId;
      result.finalText = runResult.finalResponse || this.finalText;
      result.stopReason = "completed";
    } catch (e) {
      if (this.options.abortController?.signal.aborted) {
        throw new TurnCancelledError("dsh turn cancelled");
      }
      throw e;
    } finally {
      this.options.abortController?.signal.removeEventListener("abort", onAbort);
      await harness.close().catch(() => {});
    }

    // Persist session thread
    if (result.threadId) {
      await writeStoredThread(
        this.options.stateRoot,
        "dsh",
        result.threadId,
        undefined,
        this.options.sessionScope,
      );
    }

    result.transcript = this.writer.transcript();
    if (!result.finalText && result.transcript) {
      result.finalText = result.transcript;
    }
    return result;
  }
}
